# Generated by Django 4.2.7 on 2023-12-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0005_alter_cart_cart_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="cart_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
