# Generated by Django 4.2.7 on 2023-12-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='in_guest_cart',
            field=models.BooleanField(default=False),
        ),
    ]
