# Generated by Django 4.2.7 on 2023-11-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="date_joined",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
