# Generated by Django 4.2.6 on 2024-01-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_alter_orderproduct_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Accepted", "Accepted"),
                    ("Delivered", "Delivered"),
                    ("Completed", "Completed"),
                ],
                default="New",
                max_length=10,
            ),
        ),
    ]
